version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: ./front-envoy/docker_config
    volumes:
      - ./front-envoy/front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: service-envoy-1/docker_config
    volumes:
      - ./service-envoy-1/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    build:
      context: .
      dockerfile: service-envoy-2/docker_config
    volumes:
      - ./service-envoy-2/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"

  service3:
    build:
      context: .
      dockerfile: service-envoy-3/docker_config
    volumes:
      - ./service-envoy-3/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service3
    environment:
      - SERVICE_NAME=3
    expose:
      - "80"

  service4:
    build:
      context: .
      dockerfile: service-envoy-4/docker_config
    volumes:
      - ./service-envoy-4/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service4
    environment:
      - SERVICE_NAME=4
    expose:
      - "80"

networks:
  envoymesh: {}
